name: SYCL CTS CI

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      # Run on our default base branch to prime ccache for faster CI runs in PRs.
      - main

jobs:
  check-clang-format:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0 # Need to check out base branch as well
      - name: Run clang-format on changed files
        run: |
          set -o errexit -o pipefail -o noclobber -o nounset
          DIFF=$( git diff -U0 --no-color ${{ github.event.pull_request.base.sha }} | clang-format-diff -p1 )
          if [ ! -z "$DIFF" ]; then
            echo 'The following changes are not formatted according to `clang-format`:' >> $GITHUB_STEP_SUMMARY
            echo '```diff' >> $GITHUB_STEP_SUMMARY
            echo "$DIFF" >> $GITHUB_STEP_SUMMARY
            echo '```' >> $GITHUB_STEP_SUMMARY
            echo "Not all files are formatted according to clang-format. See workflow summary for details."
            exit 1 # Fail CI run
          fi

