name: SYCL CTS CI

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      # Run on our default base branch to prime ccache for faster CI runs in PRs.
      - main

jobs:
  check-clang-format:
    if: github.event_name == 'pull_request'
    
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cpp-linter/cpp-linter-action@main
        id: linter
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          style: file
          tidy-checks: '-*' # Disable all clang-tidy checks for now. Enable checks as needed.
          lines-changed-only: true
          format-review: true
