name: SYCL CTS CI

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      # Run on our default base branch to prime ccache for faster CI runs in PRs.
      - main

jobs:
  check-clang-format:
    if: github.event_name == 'pull_request'

    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    steps:
      - uses: actions/checkout@v5
      - uses: cpp-linter/cpp-linter-action@v2
        id: linter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          style: file
          tidy-checks: '-*' # Disable all clang-tidy checks for now. Enable checks as needed.
          file-annotations: true
          lines-changed-only: true
      - name: Fail fast?!
        if: steps.linter.outputs.clang-format-checks-failed > 0
        run: exit 1

